# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created: Wed Jan 10 20:54:25 2018
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(965, 493)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 955, 465))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(955, 465))
        self.tabWidget.setMaximumSize(QtCore.QSize(791, 471))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 127);"))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.uploadGV = QtGui.QGraphicsView(self.tab_1)
        self.uploadGV.setGeometry(QtCore.QRect(20, 30, 256, 192))
        self.uploadGV.setAutoFillBackground(True)
        self.uploadGV.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV.setFrameShadow(QtGui.QFrame.Sunken)
        brush = QtGui.QBrush(QtGui.QColor(60, 150, 60))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.uploadGV.setBackgroundBrush(brush)
        self.uploadGV.setObjectName(_fromUtf8("uploadGV"))
        self.operationGV = QtGui.QGraphicsView(self.tab_1)
        self.operationGV.setGeometry(QtCore.QRect(480, 30, 256, 192))
        self.operationGV.setObjectName(_fromUtf8("operationGV"))
        self.upload_btn = QtGui.QPushButton(self.tab_1)
        self.upload_btn.setGeometry(QtCore.QRect(20, 240, 85, 27))
        self.upload_btn.setObjectName(_fromUtf8("upload_btn"))
        self.h_cevir_btn = QtGui.QPushButton(self.tab_1)
        self.h_cevir_btn.setGeometry(QtCore.QRect(200, 370, 85, 27))
        self.h_cevir_btn.setObjectName(_fromUtf8("h_cevir_btn"))
        self.v_cevir_btn = QtGui.QPushButton(self.tab_1)
        self.v_cevir_btn.setGeometry(QtCore.QRect(110, 370, 85, 27))
        self.v_cevir_btn.setObjectName(_fromUtf8("v_cevir_btn"))
        self.binary_btn = QtGui.QPushButton(self.tab_1)
        self.binary_btn.setGeometry(QtCore.QRect(20, 340, 85, 27))
        self.binary_btn.setObjectName(_fromUtf8("binary_btn"))
        self.grayScale_btn = QtGui.QPushButton(self.tab_1)
        self.grayScale_btn.setGeometry(QtCore.QRect(110, 340, 85, 27))
        self.grayScale_btn.setObjectName(_fromUtf8("grayScale_btn"))
        self.getEdge_btn = QtGui.QPushButton(self.tab_1)
        self.getEdge_btn.setGeometry(QtCore.QRect(20, 370, 85, 27))
        self.getEdge_btn.setObjectName(_fromUtf8("getEdge_btn"))
        self.resize_btn = QtGui.QPushButton(self.tab_1)
        self.resize_btn.setGeometry(QtCore.QRect(470, 290, 85, 27))
        self.resize_btn.setObjectName(_fromUtf8("resize_btn"))
        self.basic_tab_durum_lbl_2 = QtGui.QLabel(self.tab_1)
        self.basic_tab_durum_lbl_2.setGeometry(QtCore.QRect(300, 30, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.basic_tab_durum_lbl_2.setFont(font)
        self.basic_tab_durum_lbl_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.basic_tab_durum_lbl_2.setTextFormat(QtCore.Qt.AutoText)
        self.basic_tab_durum_lbl_2.setObjectName(_fromUtf8("basic_tab_durum_lbl_2"))
        self.show_px_value_btn = QtGui.QPushButton(self.tab_1)
        self.show_px_value_btn.setGeometry(QtCore.QRect(470, 360, 121, 27))
        self.show_px_value_btn.setObjectName(_fromUtf8("show_px_value_btn"))
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(570, 280, 41, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(570, 320, 41, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.dial = QtGui.QDial(self.tab_1)
        self.dial.setGeometry(QtCore.QRect(330, 50, 91, 101))
        self.dial.setMouseTracking(False)
        self.dial.setAcceptDrops(False)
        self.dial.setMaximum(360)
        self.dial.setInvertedAppearance(False)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.label_3 = QtGui.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(700, 280, 41, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(700, 320, 41, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 141, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_1)
        self.label_6.setGeometry(QtCore.QRect(480, 10, 141, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horSlider = QtGui.QSlider(self.tab_1)
        self.horSlider.setGeometry(QtCore.QRect(300, 200, 161, 20))
        self.horSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider.setObjectName(_fromUtf8("horSlider"))
        self.basic_tab_durum_lbl_3 = QtGui.QLabel(self.tab_1)
        self.basic_tab_durum_lbl_3.setGeometry(QtCore.QRect(320, 170, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.basic_tab_durum_lbl_3.setFont(font)
        self.basic_tab_durum_lbl_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.basic_tab_durum_lbl_3.setTextFormat(QtCore.Qt.AutoText)
        self.basic_tab_durum_lbl_3.setObjectName(_fromUtf8("basic_tab_durum_lbl_3"))
        self.negatif_btn = QtGui.QPushButton(self.tab_1)
        self.negatif_btn.setGeometry(QtCore.QRect(200, 340, 85, 27))
        self.negatif_btn.setObjectName(_fromUtf8("negatif_btn"))
        self.H_X_txt = QtGui.QTextEdit(self.tab_1)
        self.H_X_txt.setGeometry(QtCore.QRect(620, 270, 71, 31))
        self.H_X_txt.setObjectName(_fromUtf8("H_X_txt"))
        self.W_Y_txt = QtGui.QTextEdit(self.tab_1)
        self.W_Y_txt.setGeometry(QtCore.QRect(620, 310, 71, 31))
        self.W_Y_txt.setObjectName(_fromUtf8("W_Y_txt"))
        self.pixel_color_txt = QtGui.QTextEdit(self.tab_1)
        self.pixel_color_txt.setGeometry(QtCore.QRect(610, 360, 121, 31))
        self.pixel_color_txt.setObjectName(_fromUtf8("pixel_color_txt"))
        self.upload_H_txt = QtGui.QTextEdit(self.tab_1)
        self.upload_H_txt.setGeometry(QtCore.QRect(140, 240, 51, 31))
        self.upload_H_txt.setObjectName(_fromUtf8("upload_H_txt"))
        self.upload_w_txt = QtGui.QTextEdit(self.tab_1)
        self.upload_w_txt.setGeometry(QtCore.QRect(220, 240, 51, 31))
        self.upload_w_txt.setObjectName(_fromUtf8("upload_w_txt"))
        self.after_W_txt = QtGui.QTextEdit(self.tab_1)
        self.after_W_txt.setGeometry(QtCore.QRect(690, 230, 51, 31))
        self.after_W_txt.setObjectName(_fromUtf8("after_W_txt"))
        self.after_H_txt = QtGui.QTextEdit(self.tab_1)
        self.after_H_txt.setGeometry(QtCore.QRect(610, 230, 51, 31))
        self.after_H_txt.setObjectName(_fromUtf8("after_H_txt"))
        self.label_7 = QtGui.QLabel(self.tab_1)
        self.label_7.setGeometry(QtCore.QRect(120, 250, 16, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_1)
        self.label_8.setGeometry(QtCore.QRect(200, 250, 16, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_1)
        self.label_9.setGeometry(QtCore.QRect(670, 240, 16, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_1)
        self.label_10.setGeometry(QtCore.QRect(590, 240, 16, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_1)
        self.label_11.setGeometry(QtCore.QRect(490, 240, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.slider_value_lbl = QtGui.QLabel(self.tab_1)
        self.slider_value_lbl.setGeometry(QtCore.QRect(370, 220, 16, 21))
        self.slider_value_lbl.setObjectName(_fromUtf8("slider_value_lbl"))
        self.dial_value_lbl = QtGui.QLabel(self.tab_1)
        self.dial_value_lbl.setGeometry(QtCore.QRect(430, 90, 31, 21))
        self.dial_value_lbl.setObjectName(_fromUtf8("dial_value_lbl"))
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.upload_btn_filterTab = QtGui.QPushButton(self.tab_2)
        self.upload_btn_filterTab.setGeometry(QtCore.QRect(50, 240, 85, 27))
        self.upload_btn_filterTab.setObjectName(_fromUtf8("upload_btn_filterTab"))
        self.uploadGV_filterTab = QtGui.QGraphicsView(self.tab_2)
        self.uploadGV_filterTab.setGeometry(QtCore.QRect(50, 30, 256, 192))
        self.uploadGV_filterTab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_filterTab.setFrameShadow(QtGui.QFrame.Sunken)
        self.uploadGV_filterTab.setObjectName(_fromUtf8("uploadGV_filterTab"))
        self.operationsGV_filterTab = QtGui.QGraphicsView(self.tab_2)
        self.operationsGV_filterTab.setGeometry(QtCore.QRect(470, 30, 256, 192))
        self.operationsGV_filterTab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.operationsGV_filterTab.setFrameShadow(QtGui.QFrame.Sunken)
        self.operationsGV_filterTab.setObjectName(_fromUtf8("operationsGV_filterTab"))
        self.canny_btn_filter = QtGui.QPushButton(self.tab_2)
        self.canny_btn_filter.setGeometry(QtCore.QRect(50, 300, 85, 91))
        self.canny_btn_filter.setObjectName(_fromUtf8("canny_btn_filter"))
        self.sobel_btn_filter = QtGui.QPushButton(self.tab_2)
        self.sobel_btn_filter.setGeometry(QtCore.QRect(150, 300, 85, 91))
        self.sobel_btn_filter.setObjectName(_fromUtf8("sobel_btn_filter"))
        self.prewitt_btn_filter = QtGui.QPushButton(self.tab_2)
        self.prewitt_btn_filter.setGeometry(QtCore.QRect(250, 300, 85, 91))
        self.prewitt_btn_filter.setObjectName(_fromUtf8("prewitt_btn_filter"))
        self.filter_tab_durum_lbl = QtGui.QLabel(self.tab_2)
        self.filter_tab_durum_lbl.setGeometry(QtCore.QRect(340, 110, 101, 20))
        self.filter_tab_durum_lbl.setObjectName(_fromUtf8("filter_tab_durum_lbl"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.uploadGV_labelling = QtGui.QGraphicsView(self.tab_3)
        self.uploadGV_labelling.setGeometry(QtCore.QRect(30, 20, 256, 192))
        self.uploadGV_labelling.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_labelling.setFrameShadow(QtGui.QFrame.Sunken)
        self.uploadGV_labelling.setObjectName(_fromUtf8("uploadGV_labelling"))
        self.upload_btn_labelling = QtGui.QPushButton(self.tab_3)
        self.upload_btn_labelling.setGeometry(QtCore.QRect(30, 230, 85, 27))
        self.upload_btn_labelling.setObjectName(_fromUtf8("upload_btn_labelling"))
        self.comboBox_labelling = QtGui.QComboBox(self.tab_3)
        self.comboBox_labelling.setGeometry(QtCore.QRect(340, 90, 91, 27))
        self.comboBox_labelling.setObjectName(_fromUtf8("comboBox_labelling"))
        self.operationGV_labelling = QtGui.QGraphicsView(self.tab_3)
        self.operationGV_labelling.setGeometry(QtCore.QRect(490, 20, 256, 192))
        self.operationGV_labelling.setFrameShape(QtGui.QFrame.StyledPanel)
        self.operationGV_labelling.setFrameShadow(QtGui.QFrame.Sunken)
        self.operationGV_labelling.setObjectName(_fromUtf8("operationGV_labelling"))
        self.labelling_btn = QtGui.QPushButton(self.tab_3)
        self.labelling_btn.setGeometry(QtCore.QRect(30, 270, 85, 27))
        self.labelling_btn.setObjectName(_fromUtf8("labelling_btn"))
        self.kontrol_btn = QtGui.QPushButton(self.tab_3)
        self.kontrol_btn.setGeometry(QtCore.QRect(330, 240, 91, 41))
        self.kontrol_btn.setObjectName(_fromUtf8("kontrol_btn"))
        self.rbt_dikdort = QtGui.QRadioButton(self.tab_3)
        self.rbt_dikdort.setGeometry(QtCore.QRect(330, 300, 102, 22))
        self.rbt_dikdort.setChecked(True)
        self.rbt_dikdort.setObjectName(_fromUtf8("rbt_dikdort"))
        self.rbt_kare = QtGui.QRadioButton(self.tab_3)
        self.rbt_kare.setGeometry(QtCore.QRect(330, 330, 102, 22))
        self.rbt_kare.setObjectName(_fromUtf8("rbt_kare"))
        self.kontrol_lbl = QtGui.QLabel(self.tab_3)
        self.kontrol_lbl.setGeometry(QtCore.QRect(270, 380, 181, 20))
        self.kontrol_lbl.setObjectName(_fromUtf8("kontrol_lbl"))
        self.operationGV_labelling_match = QtGui.QGraphicsView(self.tab_3)
        self.operationGV_labelling_match.setGeometry(QtCore.QRect(490, 220, 256, 192))
        self.operationGV_labelling_match.setFrameShape(QtGui.QFrame.StyledPanel)
        self.operationGV_labelling_match.setFrameShadow(QtGui.QFrame.Sunken)
        self.operationGV_labelling_match.setObjectName(_fromUtf8("operationGV_labelling_match"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.histogram_treshold_btn = QtGui.QPushButton(self.tab_5)
        self.histogram_treshold_btn.setGeometry(QtCore.QRect(340, 30, 85, 27))
        self.histogram_treshold_btn.setObjectName(_fromUtf8("histogram_treshold_btn"))
        self.upload_btn_histogram = QtGui.QPushButton(self.tab_5)
        self.upload_btn_histogram.setGeometry(QtCore.QRect(30, 220, 85, 27))
        self.upload_btn_histogram.setObjectName(_fromUtf8("upload_btn_histogram"))
        self.uploadGV_histogram = QtGui.QGraphicsView(self.tab_5)
        self.uploadGV_histogram.setGeometry(QtCore.QRect(30, 10, 256, 192))
        self.uploadGV_histogram.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_histogram.setFrameShadow(QtGui.QFrame.Sunken)
        self.uploadGV_histogram.setObjectName(_fromUtf8("uploadGV_histogram"))
        self.operationGV_histogram = QtGui.QGraphicsView(self.tab_5)
        self.operationGV_histogram.setGeometry(QtCore.QRect(490, 10, 256, 192))
        self.operationGV_histogram.setFrameShape(QtGui.QFrame.StyledPanel)
        self.operationGV_histogram.setFrameShadow(QtGui.QFrame.Sunken)
        self.operationGV_histogram.setObjectName(_fromUtf8("operationGV_histogram"))
        self.compare_btn_histogram = QtGui.QPushButton(self.tab_5)
        self.compare_btn_histogram.setGeometry(QtCore.QRect(340, 150, 85, 27))
        self.compare_btn_histogram.setObjectName(_fromUtf8("compare_btn_histogram"))
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(330, 190, 101, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.sonuc_lbl = QtGui.QLabel(self.tab_5)
        self.sonuc_lbl.setGeometry(QtCore.QRect(280, 230, 471, 17))
        self.sonuc_lbl.setObjectName(_fromUtf8("sonuc_lbl"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.sonuc_lbl_blurify = QtGui.QLabel(self.tab_4)
        self.sonuc_lbl_blurify.setGeometry(QtCore.QRect(280, 230, 471, 17))
        self.sonuc_lbl_blurify.setObjectName(_fromUtf8("sonuc_lbl_blurify"))
        self.uploadGV_bluarify = QtGui.QGraphicsView(self.tab_4)
        self.uploadGV_bluarify.setGeometry(QtCore.QRect(30, 10, 256, 192))
        self.uploadGV_bluarify.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_bluarify.setFrameShadow(QtGui.QFrame.Sunken)
        self.uploadGV_bluarify.setObjectName(_fromUtf8("uploadGV_bluarify"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(330, 190, 101, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.upload_btn_blurify = QtGui.QPushButton(self.tab_4)
        self.upload_btn_blurify.setGeometry(QtCore.QRect(30, 220, 85, 27))
        self.upload_btn_blurify.setObjectName(_fromUtf8("upload_btn_blurify"))
        self.operationGV_bluarify = QtGui.QGraphicsView(self.tab_4)
        self.operationGV_bluarify.setGeometry(QtCore.QRect(490, 10, 256, 192))
        self.operationGV_bluarify.setFrameShape(QtGui.QFrame.StyledPanel)
        self.operationGV_bluarify.setFrameShadow(QtGui.QFrame.Sunken)
        self.operationGV_bluarify.setObjectName(_fromUtf8("operationGV_bluarify"))
        self.BlurySlider = QtGui.QSlider(self.tab_4)
        self.BlurySlider.setGeometry(QtCore.QRect(310, 50, 160, 17))
        self.BlurySlider.setOrientation(QtCore.Qt.Horizontal)
        self.BlurySlider.setObjectName(_fromUtf8("BlurySlider"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(360, 20, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lbl_slider_blur = QtGui.QLabel(self.tab_4)
        self.lbl_slider_blur.setGeometry(QtCore.QRect(370, 70, 16, 17))
        self.lbl_slider_blur.setObjectName(_fromUtf8("lbl_slider_blur"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.operationGV_logical = QtGui.QGraphicsView(self.tab_6)
        self.operationGV_logical.setGeometry(QtCore.QRect(260, 230, 256, 192))
        self.operationGV_logical.setObjectName(_fromUtf8("operationGV_logical"))
        self.uploadGV_logical = QtGui.QGraphicsView(self.tab_6)
        self.uploadGV_logical.setGeometry(QtCore.QRect(60, 30, 256, 192))
        self.uploadGV_logical.setAutoFillBackground(True)
        self.uploadGV_logical.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_logical.setFrameShadow(QtGui.QFrame.Sunken)
        brush = QtGui.QBrush(QtGui.QColor(60, 150, 60))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.uploadGV_logical.setBackgroundBrush(brush)
        self.uploadGV_logical.setObjectName(_fromUtf8("uploadGV_logical"))
        self.upload_btn_logical = QtGui.QPushButton(self.tab_6)
        self.upload_btn_logical.setGeometry(QtCore.QRect(60, 250, 85, 27))
        self.upload_btn_logical.setObjectName(_fromUtf8("upload_btn_logical"))
        self.CB_logical = QtGui.QComboBox(self.tab_6)
        self.CB_logical.setGeometry(QtCore.QRect(330, 30, 121, 31))
        self.CB_logical.setObjectName(_fromUtf8("CB_logical"))
        self.CB_logical.addItem(_fromUtf8(""))
        self.CB_logical.addItem(_fromUtf8(""))
        self.CB_logical.addItem(_fromUtf8(""))
        self.CB_logical.addItem(_fromUtf8(""))
        self.uploadGV_logical_2 = QtGui.QGraphicsView(self.tab_6)
        self.uploadGV_logical_2.setGeometry(QtCore.QRect(470, 30, 256, 192))
        self.uploadGV_logical_2.setAutoFillBackground(True)
        self.uploadGV_logical_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_logical_2.setFrameShadow(QtGui.QFrame.Sunken)
        brush = QtGui.QBrush(QtGui.QColor(60, 150, 60))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.uploadGV_logical_2.setBackgroundBrush(brush)
        self.uploadGV_logical_2.setObjectName(_fromUtf8("uploadGV_logical_2"))
        self.upload_btn_logical_2 = QtGui.QPushButton(self.tab_6)
        self.upload_btn_logical_2.setGeometry(QtCore.QRect(640, 240, 85, 27))
        self.upload_btn_logical_2.setObjectName(_fromUtf8("upload_btn_logical_2"))
        self.operate_btn_logical = QtGui.QPushButton(self.tab_6)
        self.operate_btn_logical.setGeometry(QtCore.QRect(350, 190, 85, 27))
        self.operate_btn_logical.setObjectName(_fromUtf8("operate_btn_logical"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.upload_btn_ErDil = QtGui.QPushButton(self.tab_7)
        self.upload_btn_ErDil.setGeometry(QtCore.QRect(30, 310, 85, 27))
        self.upload_btn_ErDil.setObjectName(_fromUtf8("upload_btn_ErDil"))
        self.uploadGV_ErDil = QtGui.QGraphicsView(self.tab_7)
        self.uploadGV_ErDil.setGeometry(QtCore.QRect(30, 90, 256, 192))
        self.uploadGV_ErDil.setAutoFillBackground(True)
        self.uploadGV_ErDil.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uploadGV_ErDil.setFrameShadow(QtGui.QFrame.Sunken)
        brush = QtGui.QBrush(QtGui.QColor(60, 150, 60))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.uploadGV_ErDil.setBackgroundBrush(brush)
        self.uploadGV_ErDil.setObjectName(_fromUtf8("uploadGV_ErDil"))
        self.operationGV_ErDil = QtGui.QGraphicsView(self.tab_7)
        self.operationGV_ErDil.setGeometry(QtCore.QRect(500, 90, 256, 192))
        self.operationGV_ErDil.setAutoFillBackground(True)
        self.operationGV_ErDil.setFrameShape(QtGui.QFrame.StyledPanel)
        self.operationGV_ErDil.setFrameShadow(QtGui.QFrame.Sunken)
        brush = QtGui.QBrush(QtGui.QColor(60, 150, 60))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.operationGV_ErDil.setBackgroundBrush(brush)
        self.operationGV_ErDil.setObjectName(_fromUtf8("operationGV_ErDil"))
        self.erode_btn_ErDil = QtGui.QPushButton(self.tab_7)
        self.erode_btn_ErDil.setGeometry(QtCore.QRect(350, 120, 85, 27))
        self.erode_btn_ErDil.setObjectName(_fromUtf8("erode_btn_ErDil"))
        self.dilation_btn_ErDil = QtGui.QPushButton(self.tab_7)
        self.dilation_btn_ErDil.setGeometry(QtCore.QRect(350, 200, 85, 27))
        self.dilation_btn_ErDil.setObjectName(_fromUtf8("dilation_btn_ErDil"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.TM_upload_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_upload_GV.setGeometry(QtCore.QRect(10, 10, 211, 181))
        self.TM_upload_GV.setObjectName(_fromUtf8("TM_upload_GV"))
        self.TM_upload_btn = QtGui.QPushButton(self.tab_8)
        self.TM_upload_btn.setGeometry(QtCore.QRect(10, 220, 81, 31))
        self.TM_upload_btn.setObjectName(_fromUtf8("TM_upload_btn"))
        self.TM_goruntuler_CB = QtGui.QComboBox(self.tab_8)
        self.TM_goruntuler_CB.setGeometry(QtCore.QRect(110, 220, 111, 31))
        self.TM_goruntuler_CB.setObjectName(_fromUtf8("TM_goruntuler_CB"))
        self.TM_arananSekil_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_arananSekil_GV.setGeometry(QtCore.QRect(110, 300, 111, 91))
        self.TM_arananSekil_GV.setObjectName(_fromUtf8("TM_arananSekil_GV"))
        self.TM_tempMatch_btn = QtGui.QPushButton(self.tab_8)
        self.TM_tempMatch_btn.setGeometry(QtCore.QRect(10, 300, 81, 91))
        self.TM_tempMatch_btn.setObjectName(_fromUtf8("TM_tempMatch_btn"))
        self.TM_1_2_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_1_2_GV.setGeometry(QtCore.QRect(350, 40, 111, 91))
        self.TM_1_2_GV.setObjectName(_fromUtf8("TM_1_2_GV"))
        self.TM_1_1_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_1_1_GV.setGeometry(QtCore.QRect(240, 40, 111, 91))
        self.TM_1_1_GV.setObjectName(_fromUtf8("TM_1_1_GV"))
        self.TM_1_3_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_1_3_GV.setGeometry(QtCore.QRect(460, 40, 111, 91))
        self.TM_1_3_GV.setObjectName(_fromUtf8("TM_1_3_GV"))
        self.TM_4_1_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_4_1_GV.setGeometry(QtCore.QRect(610, 40, 111, 91))
        self.TM_4_1_GV.setObjectName(_fromUtf8("TM_4_1_GV"))
        self.TM_4_3_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_4_3_GV.setGeometry(QtCore.QRect(830, 40, 111, 91))
        self.TM_4_3_GV.setObjectName(_fromUtf8("TM_4_3_GV"))
        self.TM_4_2_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_4_2_GV.setGeometry(QtCore.QRect(720, 40, 111, 91))
        self.TM_4_2_GV.setObjectName(_fromUtf8("TM_4_2_GV"))
        self.TM_2_1_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_2_1_GV.setGeometry(QtCore.QRect(240, 170, 111, 91))
        self.TM_2_1_GV.setObjectName(_fromUtf8("TM_2_1_GV"))
        self.TM_2_3_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_2_3_GV.setGeometry(QtCore.QRect(460, 170, 111, 91))
        self.TM_2_3_GV.setObjectName(_fromUtf8("TM_2_3_GV"))
        self.TM_2_2_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_2_2_GV.setGeometry(QtCore.QRect(350, 170, 111, 91))
        self.TM_2_2_GV.setObjectName(_fromUtf8("TM_2_2_GV"))
        self.TM_5_1_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_5_1_GV.setGeometry(QtCore.QRect(610, 170, 111, 91))
        self.TM_5_1_GV.setObjectName(_fromUtf8("TM_5_1_GV"))
        self.TM_5_3_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_5_3_GV.setGeometry(QtCore.QRect(830, 170, 111, 91))
        self.TM_5_3_GV.setObjectName(_fromUtf8("TM_5_3_GV"))
        self.TM_5_2_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_5_2_GV.setGeometry(QtCore.QRect(720, 170, 111, 91))
        self.TM_5_2_GV.setObjectName(_fromUtf8("TM_5_2_GV"))
        self.TM_6_1_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_6_1_GV.setGeometry(QtCore.QRect(610, 300, 111, 91))
        self.TM_6_1_GV.setObjectName(_fromUtf8("TM_6_1_GV"))
        self.TM_6_3_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_6_3_GV.setGeometry(QtCore.QRect(830, 300, 111, 91))
        self.TM_6_3_GV.setObjectName(_fromUtf8("TM_6_3_GV"))
        self.TM_6_2_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_6_2_GV.setGeometry(QtCore.QRect(720, 300, 111, 91))
        self.TM_6_2_GV.setObjectName(_fromUtf8("TM_6_2_GV"))
        self.TM_3_1_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_3_1_GV.setGeometry(QtCore.QRect(240, 300, 111, 91))
        self.TM_3_1_GV.setObjectName(_fromUtf8("TM_3_1_GV"))
        self.TM_3_3_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_3_3_GV.setGeometry(QtCore.QRect(460, 300, 111, 91))
        self.TM_3_3_GV.setObjectName(_fromUtf8("TM_3_3_GV"))
        self.TM_3_2_GV = QtGui.QGraphicsView(self.tab_8)
        self.TM_3_2_GV.setGeometry(QtCore.QRect(350, 300, 111, 91))
        self.TM_3_2_GV.setObjectName(_fromUtf8("TM_3_2_GV"))
        self.label_15 = QtGui.QLabel(self.tab_8)
        self.label_15.setGeometry(QtCore.QRect(110, 200, 71, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_8)
        self.label_16.setGeometry(QtCore.QRect(110, 280, 91, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_8)
        self.label_17.setGeometry(QtCore.QRect(240, 20, 81, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_20 = QtGui.QLabel(self.tab_8)
        self.label_20.setGeometry(QtCore.QRect(240, 150, 81, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.TM_bnzr3_lbl = QtGui.QLabel(self.tab_8)
        self.TM_bnzr3_lbl.setGeometry(QtCore.QRect(380, 280, 191, 20))
        self.TM_bnzr3_lbl.setObjectName(_fromUtf8("TM_bnzr3_lbl"))
        self.label_22 = QtGui.QLabel(self.tab_8)
        self.label_22.setGeometry(QtCore.QRect(240, 280, 131, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_8)
        self.label_23.setGeometry(QtCore.QRect(610, 20, 131, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.TM_bnzr4_lbl = QtGui.QLabel(self.tab_8)
        self.TM_bnzr4_lbl.setGeometry(QtCore.QRect(750, 20, 191, 20))
        self.TM_bnzr4_lbl.setObjectName(_fromUtf8("TM_bnzr4_lbl"))
        self.label_25 = QtGui.QLabel(self.tab_8)
        self.label_25.setGeometry(QtCore.QRect(610, 150, 131, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.TM_bnzr5_lbl = QtGui.QLabel(self.tab_8)
        self.TM_bnzr5_lbl.setGeometry(QtCore.QRect(750, 150, 191, 20))
        self.TM_bnzr5_lbl.setObjectName(_fromUtf8("TM_bnzr5_lbl"))
        self.label_27 = QtGui.QLabel(self.tab_8)
        self.label_27.setGeometry(QtCore.QRect(610, 280, 81, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.TM_bnzr2_lbl = QtGui.QLabel(self.tab_8)
        self.TM_bnzr2_lbl.setGeometry(QtCore.QRect(380, 150, 191, 20))
        self.TM_bnzr2_lbl.setObjectName(_fromUtf8("TM_bnzr2_lbl"))
        self.TM_bnzr1_lbl = QtGui.QLabel(self.tab_8)
        self.TM_bnzr1_lbl.setGeometry(QtCore.QRect(380, 20, 191, 20))
        self.TM_bnzr1_lbl.setObjectName(_fromUtf8("TM_bnzr1_lbl"))
        self.TM_bnzr6_lbl = QtGui.QLabel(self.tab_8)
        self.TM_bnzr6_lbl.setGeometry(QtCore.QRect(750, 280, 191, 20))
        self.TM_bnzr6_lbl.setObjectName(_fromUtf8("TM_bnzr6_lbl"))
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Umedzhon Izbasarov", None))
        self.upload_btn.setText(_translate("Form", "Upload", None))
        self.h_cevir_btn.setText(_translate("Form", "Ters Cevir", None))
        self.v_cevir_btn.setText(_translate("Form", "Aynalama", None))
        self.binary_btn.setText(_translate("Form", "ikili", None))
        self.grayScale_btn.setText(_translate("Form", "gri", None))
        self.getEdge_btn.setText(_translate("Form", "kenar", None))
        self.resize_btn.setText(_translate("Form", "Resize", None))
        self.basic_tab_durum_lbl_2.setText(_translate("Form", "   Goruntuyu Dondurme", None))
        self.show_px_value_btn.setText(_translate("Form", "Pikselleri Goster", None))
        self.label.setText(_translate("Form", "Height", None))
        self.label_2.setText(_translate("Form", "Width", None))
        self.label_3.setText(_translate("Form", "X pix", None))
        self.label_4.setText(_translate("Form", "Y pix", None))
        self.label_5.setText(_translate("Form", "Yuklenen Goruntu", None))
        self.label_6.setText(_translate("Form", "Sonuc Goruntu", None))
        self.basic_tab_durum_lbl_3.setText(_translate("Form", "  Bulaniklik Verme", None))
        self.negatif_btn.setText(_translate("Form", "negatif", None))
        self.label_7.setText(_translate("Form", "H", None))
        self.label_8.setText(_translate("Form", "W", None))
        self.label_9.setText(_translate("Form", "W", None))
        self.label_10.setText(_translate("Form", "H", None))
        self.label_11.setText(_translate("Form", "Sonuc boyut :", None))
        self.slider_value_lbl.setText(_translate("Form", "0", None))
        self.dial_value_lbl.setText(_translate("Form", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", " Basic Operation ", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_1), _translate("Form", "<html><head/><body><p>Temel Islemler Bulunur ( gray image, binary, resize, pikselleri gosterme, rotate)</p></body></html>", None))
        self.upload_btn_filterTab.setText(_translate("Form", "Upload", None))
        self.canny_btn_filter.setText(_translate("Form", "Canny", None))
        self.sobel_btn_filter.setText(_translate("Form", "Sobel", None))
        self.prewitt_btn_filter.setText(_translate("Form", "Prewitt", None))
        self.filter_tab_durum_lbl.setText(_translate("Form", "  Islem Durumu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", " Filtering ", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("Form", "<html><head/><body><p>Canny, Sobel, Prewit ile filtrelemeler.</p></body></html>", None))
        self.upload_btn_labelling.setText(_translate("Form", "Upload", None))
        self.labelling_btn.setText(_translate("Form", "Labelling", None))
        self.kontrol_btn.setText(_translate("Form", "Kontrol", None))
        self.rbt_dikdort.setText(_translate("Form", "Dikdortgen", None))
        self.rbt_kare.setText(_translate("Form", "Kare", None))
        self.kontrol_lbl.setText(_translate("Form", "Kontrol Sonuc :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", " Labelling", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("Form", "<html><head/><body><p>a) bu sekil karedir veya degildir! Tespiti</p><p>b) kare mi dikdortgen mi kod ile fonksiyon yazma</p></body></html>", None))
        self.histogram_treshold_btn.setText(_translate("Form", "Threshold", None))
        self.upload_btn_histogram.setText(_translate("Form", "Upload", None))
        self.compare_btn_histogram.setText(_translate("Form", "Compare", None))
        self.label_12.setText(_translate("Form", "Measurements:", None))
        self.sonuc_lbl.setText(_translate("Form", " : )", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Histogram", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_5), _translate("Form", "<html><head/><body><p>Histogram esitleme ve orijinal goruntu uzerinde benzerliklerini karsilastir.</p></body></html>", None))
        self.sonuc_lbl_blurify.setText(_translate("Form", " : )", None))
        self.label_13.setText(_translate("Form", "Measurements:", None))
        self.upload_btn_blurify.setText(_translate("Form", "Upload", None))
        self.label_14.setText(_translate("Form", "Blurify", None))
        self.lbl_slider_blur.setText(_translate("Form", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Blury Image Comparison", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate("Form", "<html><head/><body><p>%10 ile %60 kadar sirasiyla olusturulan gorultulu resimleri ile orijinal resimleri karsilastirarak benzerliklerini SSIM, MSE ve PSNR ile bulmak</p></body></html>", None))
        self.upload_btn_logical.setText(_translate("Form", "Upload", None))
        self.CB_logical.setItemText(0, _translate("Form", "AND", None))
        self.CB_logical.setItemText(1, _translate("Form", "NOT", None))
        self.CB_logical.setItemText(2, _translate("Form", "XOR", None))
        self.CB_logical.setItemText(3, _translate("Form", "OR", None))
        self.upload_btn_logical_2.setText(_translate("Form", "Upload", None))
        self.operate_btn_logical.setText(_translate("Form", "Operate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "Logical Operation", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_6), _translate("Form", "<html><head/><body><p>and, or ... gibi mantiksal islemler</p></body></html>", None))
        self.upload_btn_ErDil.setText(_translate("Form", "Upload", None))
        self.erode_btn_ErDil.setText(_translate("Form", "Erode", None))
        self.dilation_btn_ErDil.setText(_translate("Form", "Dilation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "Erosion-Dilation", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_7), _translate("Form", "<html><head/><body><p>zaten yaziyor orda armut!</p></body></html>", None))
        self.TM_upload_btn.setText(_translate("Form", "Upload", None))
        self.TM_tempMatch_btn.setText(_translate("Form", "Template\n"
"Matching", None))
        self.label_15.setText(_translate("Form", "Goruntuler", None))
        self.label_16.setText(_translate("Form", "Aranan Sekil", None))
        self.label_17.setText(_translate("Form", "TM CCOEFF", None))
        self.label_20.setText(_translate("Form", "TM SQDIFF", None))
        self.TM_bnzr3_lbl.setText(_translate("Form", "BENZERLIK", None))
        self.label_22.setText(_translate("Form", "TM SQDIFF NORMED", None))
        self.label_23.setText(_translate("Form", "TM CCOEFF NORMED", None))
        self.TM_bnzr4_lbl.setText(_translate("Form", "BENZERLIK", None))
        self.label_25.setText(_translate("Form", "TM CCORR NORMED", None))
        self.TM_bnzr5_lbl.setText(_translate("Form", "BENZERLIK", None))
        self.label_27.setText(_translate("Form", "TM CCORR", None))
        self.TM_bnzr2_lbl.setText(_translate("Form", "BENZERLIK", None))
        self.TM_bnzr1_lbl.setText(_translate("Form", "BENZERLIK", None))
        self.TM_bnzr6_lbl.setText(_translate("Form", "BENZERLIK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Form", "Template Matching", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_8), _translate("Form", "<html><head/><body><p>goruntude aranan goruntuyu bulacagiz!</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Form", "Face detection", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_9), _translate("Form", "<html><head/><body><p>face detection ile sinif ogrencilerinin tespiti yapacagiz.</p><p>a) DB olan veriler ile karsilastirma</p><p>b) gun-gun ogrencilerin sistemde devamlilik verilerini islemek</p></body></html>", None))

